# Generated by Django 5.2.8 on 2025-12-01 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Học viên'), ('TEACHER', 'Giáo viên'), ('ADMIN', 'Giáo vụ/Quản trị viên')], db_index=True, default='STUDENT', help_text='Vai trò của người dùng trong hệ thống', max_length=20, verbose_name='Vai trò')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='Ảnh đại diện')),
                ('bio', models.TextField(blank=True, verbose_name='Giới thiệu bản thân')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
                'db_table': 'user_profile',
                'ordering': ['role', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='AuthAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('EXPIRED', 'Đã hết hạn'), ('REVOKED', 'Đã thu hồi')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('access_code', models.CharField(blank=True, help_text='Mã code để kích hoạt quyền truy cập (nếu có)', max_length=50, verbose_name='Mã truy cập')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Có hiệu lực từ')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Để trống nếu không giới hạn thời gian', null=True, verbose_name='Có hiệu lực đến')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú về việc phân quyền', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin/Teacher đã tạo phân quyền này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Được gán bởi')),
                ('program', models.ForeignKey(blank=True, help_text='Gán quyền cho toàn bộ chương trình', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_assignments', to='content.program', verbose_name='Chương trình học')),
                ('subcourse', models.ForeignKey(blank=True, help_text='Gán quyền cho khóa học cụ thể', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_assignments', to='content.subcourse', verbose_name='Khóa học con')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phân quyền truy cập',
                'verbose_name_plural': 'Phân quyền truy cập',
                'db_table': 'auth_assignment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='auth_assign_user_id_069bcc_idx'), models.Index(fields=['program', 'status'], name='auth_assign_program_bd3c44_idx'), models.Index(fields=['subcourse', 'status'], name='auth_assign_subcour_9af6a2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('program__isnull', False), ('subcourse__isnull', False), _connector='OR'), name='auth_assignment_requires_program_or_subcourse')],
            },
        ),
    ]
