# Generated by Django 5.2.8 on 2025-12-01 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Lập trình SPIKE Essential Cơ bản', max_length=255, verbose_name='Tên chương trình')),
                ('slug', models.SlugField(help_text='Tự động tạo từ tên chương trình', max_length=255, unique=True, verbose_name='Đường dẫn URL')),
                ('description', models.TextField(blank=True, help_text='Mô tả tổng quan về chương trình học', verbose_name='Mô tả')),
                ('kit_type', models.CharField(choices=[('SPIKE_ESSENTIAL', 'SPIKE Essential'), ('SPIKE_PRIME', 'SPIKE Prime')], help_text='Chọn loại kit LEGO sử dụng', max_length=50, verbose_name='Loại bộ kit')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL ảnh thumbnail từ Object Storage', max_length=500, verbose_name='Ảnh đại diện')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã xuất bản'), ('ARCHIVED', 'Đã lưu trữ')], db_index=True, default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('sort_order', models.IntegerField(default=1, help_text='Số thứ tự hiển thị (nhỏ hơn = hiển thị trước)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự sắp xếp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chương trình học',
                'verbose_name_plural': 'Chương trình học',
                'db_table': 'programs',
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['status', 'sort_order'], name='programs_status_10617a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Module 1 - Làm quen với Robot', max_length=255, verbose_name='Tên khóa con')),
                ('slug', models.SlugField(max_length=255, verbose_name='Đường dẫn URL')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ')),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về khóa học con', verbose_name='Mô tả')),
                ('coding_language', models.CharField(choices=[('ICON_BLOCKS', 'Icon Blocks'), ('WORD_BLOCKS', 'Word Blocks'), ('PYTHON', 'Python')], help_text='Chọn ngôn ngữ lập trình sử dụng', max_length=50, verbose_name='Ngôn ngữ lập trình')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='Ảnh đại diện')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã xuất bản'), ('ARCHIVED', 'Đã lưu trữ')], db_index=True, default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('sort_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự sắp xếp')),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='Để 0 nếu miễn phí', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá khóa học (VNĐ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcourses', to='content.program', verbose_name='Chương trình học')),
            ],
            options={
                'verbose_name': 'Khóa học con',
                'verbose_name_plural': 'Khóa học con',
                'db_table': 'subcourses',
                'ordering': ['program', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Bài 1 - Xây dựng robot đầu tiên', max_length=255, verbose_name='Tên bài học')),
                ('slug', models.SlugField(max_length=255, verbose_name='Đường dẫn URL')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ')),
                ('objective', models.TextField(blank=True, help_text='Học viên sẽ đạt được gì sau bài học này?', verbose_name='Mục tiêu bài học')),
                ('knowledge_skills', models.TextField(blank=True, help_text='Kiến thức và kỹ năng cần đạt được', verbose_name='Kiến thức & Kỹ năng')),
                ('content_text', models.TextField(blank=True, help_text='Nội dung text/HTML của bài học', verbose_name='Nội dung bài học')),
                ('video_url', models.URLField(blank=True, help_text='Link video hướng dẫn từ S3/GCS', max_length=500, verbose_name='URL Video')),
                ('project_file_url', models.URLField(blank=True, help_text='Link file .llsp hoặc .py từ S3/GCS', max_length=500, verbose_name='URL File dự án')),
                ('code_snippet', models.TextField(blank=True, help_text='Code mẫu để học viên tham khảo', verbose_name='Code mẫu')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã xuất bản'), ('ARCHIVED', 'Đã lưu trữ')], db_index=True, default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('sort_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự sắp xếp')),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Thời gian ước tính để hoàn thành bài học', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thời lượng (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('subcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.subcourse', verbose_name='Khóa học con')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Bài học',
                'db_table': 'lessons',
                'ordering': ['subcourse', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Đã hoàn thành')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='content.lesson', verbose_name='Bài học')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Tiến độ học tập',
                'verbose_name_plural': 'Tiến độ học tập',
                'db_table': 'user_progress',
            },
        ),
        migrations.AddIndex(
            model_name='subcourse',
            index=models.Index(fields=['program', 'status', 'sort_order'], name='subcourses_program_398b56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcourse',
            unique_together={('program', 'slug')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['subcourse', 'status', 'sort_order'], name='lessons_subcour_bd1780_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subcourse', 'slug')},
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'is_completed'], name='user_progre_user_id_c01ae6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'lesson')},
        ),
    ]
