# Generated by Django 4.2.27 on 2025-12-25 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên hướng dẫn lắp ráp')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('pdf_url', models.URLField(blank=True, help_text='Link PDF hướng dẫn lắp ráp (optional)', max_length=500, null=True, verbose_name='Link PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Hướng dẫn lắp ráp',
                'verbose_name_plural': 'Hướng dẫn lắp ráp',
                'db_table': 'assembly_guides',
                'ordering': ['lesson', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BuildBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên khối xây dựng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('pdf_url', models.URLField(blank=True, help_text='Link PDF hoặc PNG', max_length=500, null=True, verbose_name='Link ảnh  ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khối xây dựng',
                'verbose_name_plural': 'Khối xây dựng',
                'db_table': 'build_blocks',
                'ordering': ['program', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên thử thách')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ')),
                ('description', models.TextField(help_text='Mô tả bài tập/thử thách', verbose_name='Mô tả chi tiết')),
                ('instructions', models.TextField(help_text='Các bước thực hiện chi tiết', verbose_name='Hướng dẫn')),
                ('expected_output', models.TextField(blank=True, help_text='Kết quả robot/chương trình nên đạt được', verbose_name='Kết quả mong đợi')),
                ('difficulty', models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó'), ('expert', 'Chuyên gia')], db_index=True, default='medium', max_length=20, verbose_name='Độ khó')),
                ('points', models.IntegerField(default=10, help_text='Điểm tối đa khi hoàn thành', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm thưởng')),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Thời gian tối đa để hoàn thành (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Giới hạn thời gian (phút)')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Đã lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Thử thách',
                'verbose_name_plural': 'Thử thách',
                'db_table': 'challenges',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Bài 1 - Xây dựng robot đầu tiên', max_length=255, verbose_name='Tên bài học')),
                ('slug', models.SlugField(max_length=255, verbose_name='Đường dẫn URL')),
                ('objective', models.TextField(blank=True, help_text='Học viên sẽ đạt được gì sau bài học này?', verbose_name='Mục tiêu bài học')),
                ('knowledge_skills', models.TextField(blank=True, help_text='Các kiến thức và kỹ năng học được trong bài học', verbose_name='Kiến thức & Kỹ năng')),
                ('content_text', models.TextField(blank=True, help_text='Nội dung text/HTML của bài học', verbose_name='Nội dung bài học')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã xuất bản'), ('ARCHIVED', 'Đã lưu trữ')], db_index=True, default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('sort_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự sắp xếp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Bài học',
                'db_table': 'lessons',
                'ordering': ['subcourse', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file', models.FileField(upload_to='lessons/attachments/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Ảnh'), ('video', 'Video'), ('code', 'Code'), ('other', 'Khác')], max_length=20, verbose_name='Loại file')),
                ('file_size_kb', models.IntegerField(default=0, verbose_name='Kích thước (KB)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Tệp đính kèm',
                'verbose_name_plural': 'Tệp đính kèm',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề khối nội dung')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ')),
                ('content_type', models.CharField(choices=[('text', 'Văn bản'), ('text_media', 'Văn bản + Media'), ('video', 'Video'), ('example', 'Ví dụ code/bài tập'), ('tips', 'Mẹo vặt'), ('summary', 'Tóm tắt')], default='text_media', max_length=20, verbose_name='Loại nội dung')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả/Giải thích chính')),
                ('usage_text', models.TextField(blank=True, help_text='Cách sử dụng / cách áp dụng nội dung này', verbose_name='Hướng dẫn sử dụng')),
                ('example_text', models.TextField(blank=True, help_text='Code, công thức hoặc ví dụ cụ thể', verbose_name='Ví dụ minh họa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khối nội dung',
                'verbose_name_plural': 'Khối nội dung',
                'db_table': 'lesson_content_blocks',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên mô hình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả mô hình')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Mô hình bài học',
                'verbose_name_plural': 'Mô hình bài học',
                'db_table': 'lesson_models',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_type', models.CharField(choices=[('knowledge', 'Kiến thức (Knowledge)'), ('thinking', 'Tư duy (Thinking)'), ('skills', 'Kỹ năng (Skills)'), ('attitude', 'Thái độ (Attitude)')], db_index=True, max_length=20, verbose_name='Loại mục tiêu')),
                ('text', models.TextField(help_text='Mô tả chi tiết mục tiêu học tập', verbose_name='Mô tả mục tiêu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Mục tiêu bài học',
                'verbose_name_plural': 'Mục tiêu bài học',
                'db_table': 'lesson_objectives',
                'ordering': ['lesson', 'objective_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL Media')),
                ('media_type', models.CharField(choices=[('image', 'Hình ảnh (JPG/PNG)'), ('video', 'Video (MP4/WebM)'), ('pdf', 'PDF Document'), ('animation', '3D Animation/GIF'), ('file', 'File khác')], db_index=True, max_length=20, verbose_name='Loại Media')),
                ('caption', models.CharField(blank=True, help_text='Chú thích hoặc mô tả ngắn của media', max_length=255, verbose_name='Chú thích')),
                ('alt_text', models.CharField(blank=True, help_text='Văn bản thay thế cho hình ảnh (SEO & A11y)', max_length=255, verbose_name='Alt Text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sắp xếp media theo thứ tự (0 = không có thứ tự cố định)', verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chuẩn bị bài học',
                'verbose_name_plural': 'Chuẩn bị bài học',
                'db_table': 'preparations',
                'ordering': ['lesson'],
            },
        ),
        migrations.CreateModel(
            name='PreparationBuildBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Số lượng khối cần chuẩn bị cho bài học', verbose_name='Số lượng cần chuẩn bị')),
            ],
            options={
                'verbose_name': 'Khối chuẩn bị',
                'verbose_name_plural': 'Khối chuẩn bị',
                'db_table': 'preparations_build_blocks',
                'ordering': ['preparation', 'build_block__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Lập trình SPIKE Essential Cơ bản', max_length=255, verbose_name='Tên chương trình')),
                ('slug', models.SlugField(help_text='Tự động tạo từ tên chương trình', max_length=255, unique=True, verbose_name='Đường dẫn URL')),
                ('description', models.TextField(blank=True, help_text='Mô tả tổng quan về chương trình học', verbose_name='Mô tả')),
                ('kit_type', models.CharField(choices=[('SPIKE_ESSENTIAL', 'SPIKE Essential'), ('SPIKE_PRIME', 'SPIKE Prime')], help_text='Chọn loại kit LEGO sử dụng', max_length=50, verbose_name='Loại bộ kit')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL ảnh thumbnail từ Object Storage', max_length=500, verbose_name='Ảnh đại diện')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã xuất bản'), ('ARCHIVED', 'Đã lưu trữ')], db_index=True, default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('sort_order', models.IntegerField(default=1, help_text='Số thứ tự hiển thị (nhỏ hơn = hiển thị trước)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự sắp xếp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chương trình học',
                'verbose_name_plural': 'Chương trình học',
                'db_table': 'programs',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên quiz/bài kiểm tra')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả quiz')),
                ('quiz_type', models.CharField(choices=[('single', 'Một lựa chọn'), ('multiple', 'Nhiều lựa chọn'), ('open', 'Câu hỏi mở'), ('mixed', 'Hỗn hợp')], default='mixed', max_length=20, verbose_name='Loại quiz')),
                ('passing_score', models.IntegerField(default=70, help_text='Điểm phần trăm tối thiểu để vượt qua', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm vượt qua (%)')),
                ('max_attempts', models.IntegerField(default=3, help_text='Số lần học viên được phép làm quiz', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lần làm bài tối đa')),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Thời gian tối đa để hoàn thành (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Giới hạn thời gian (phút)')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Xáo trộn câu hỏi')),
                ('shuffle_options', models.BooleanField(default=True, verbose_name='Xáo trộn lựa chọn')),
                ('show_correct_answer', models.BooleanField(default=True, verbose_name='Hiển thị đáp án đúng')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã xuất bản'), ('archived', 'Đã lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.lesson', verbose_name='Bài học')),
            ],
            options={
                'verbose_name': 'Bài kiểm tra',
                'verbose_name_plural': 'Bài kiểm tra',
                'db_table': 'quizzes',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Đã hoàn thành')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='content.lesson', verbose_name='Bài học')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Tiến độ học tập',
                'verbose_name_plural': 'Tiến độ học tập',
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='Subcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Module 1 - Làm quen với Robot', max_length=255, verbose_name='Tên khóa con')),
                ('slug', models.SlugField(max_length=255, verbose_name='Đường dẫn URL')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ')),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về khóa học con', verbose_name='Mô tả')),
                ('objective', models.TextField(blank=True, help_text='Mục tiêu học tập - những gì học viên sẽ đạt được', verbose_name='Mục tiêu')),
                ('coding_language', models.CharField(choices=[('ICON_BLOCKS', 'Icon Blocks'), ('WORD_BLOCKS', 'Word Blocks'), ('PYTHON', 'Python')], help_text='Chọn ngôn ngữ lập trình sử dụng', max_length=50, verbose_name='Ngôn ngữ lập trình')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='Ảnh đại diện')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Đã xuất bản'), ('ARCHIVED', 'Đã lưu trữ')], db_index=True, default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('sort_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự sắp xếp')),
                ('level', models.CharField(choices=[('BEGINNER', 'Sơ cấp'), ('INTERMEDIATE', 'Trung cấp'), ('ADVANCED', 'Nâng cao')], default='BEGINNER', help_text='Sơ cấp, Trung cấp, hoặc Nâng cao', max_length=20, verbose_name='Cấp độ')),
                ('level_number', models.IntegerField(default=1, help_text='Level 1, Level 2, Level 3, ...', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level')),
                ('session_count', models.IntegerField(default=20, help_text='Tổng số buổi học trong khóa học này', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng buổi học')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcourses', to='content.program', verbose_name='Chương trình học')),
            ],
            options={
                'verbose_name': 'Khóa học con',
                'verbose_name_plural': 'Khóa học con',
                'db_table': 'subcourses',
                'ordering': ['program', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, help_text='Điểm nhận được (nếu đã chấm)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm số')),
                ('max_score', models.IntegerField(blank=True, help_text='Tổng điểm tối đa của quiz', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Điểm tối đa')),
                ('percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Phần trăm (%)')),
                ('status', models.CharField(choices=[('in_progress', 'Đang làm'), ('submitted', 'Đã nộp'), ('graded', 'Đã chấm')], default='in_progress', max_length=20, verbose_name='Trạng thái')),
                ('is_passed', models.BooleanField(db_index=True, default=False, verbose_name='Đã vượt qua')),
                ('attempt_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lần thứ')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nộp')),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thời gian làm (giây)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Bài nộp quiz',
                'verbose_name_plural': 'Bài nộp quiz',
                'db_table': 'quiz_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('question_type', models.CharField(choices=[('single', 'Một lựa chọn'), ('multiple', 'Nhiều lựa chọn'), ('open', 'Câu hỏi mở')], default='single', max_length=20, verbose_name='Loại câu hỏi')),
                ('explanation', models.TextField(blank=True, help_text='Giải thích đáp án sau khi nộp bài', verbose_name='Giải thích')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm số')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự câu hỏi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Câu hỏi quiz',
                'verbose_name_plural': 'Câu hỏi quiz',
                'db_table': 'quiz_questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_ids', models.JSONField(blank=True, default=list, help_text='[1, 2, 3] cho multiple choice', verbose_name='IDs lựa chọn được chọn')),
                ('answer_text', models.TextField(blank=True, help_text='Câu trả lời dạng text cho câu hỏi mở', verbose_name='Trả lời mở')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='Câu trả lời đúng')),
                ('points_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm nhận được')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.quizquestion', verbose_name='Câu hỏi')),
                ('quiz_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.quizsubmission', verbose_name='Bài nộp quiz')),
            ],
            options={
                'verbose_name': 'Câu trả lời',
                'verbose_name_plural': 'Câu trả lời',
                'db_table': 'quiz_answers',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(verbose_name='Nội dung lựa chọn')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='Là đáp án đúng')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.quizquestion', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Lựa chọn câu hỏi',
                'verbose_name_plural': 'Lựa chọn câu hỏi',
                'db_table': 'question_options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['status', 'sort_order'], name='programs_status_10617a_idx'),
        ),
        migrations.AddField(
            model_name='preparationbuildblock',
            name='build_block',
            field=models.ForeignKey(db_column='buildblock_id', on_delete=django.db.models.deletion.CASCADE, related_name='preparation_build_blocks', to='content.buildblock', verbose_name='Khối xây dựng'),
        ),
        migrations.AddField(
            model_name='preparationbuildblock',
            name='preparation',
            field=models.ForeignKey(db_column='preparation_id', on_delete=django.db.models.deletion.CASCADE, related_name='preparation_build_blocks', to='content.preparation', verbose_name='Chuẩn bị'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='build_blocks',
            field=models.ManyToManyField(blank=True, help_text='Chọn các build blocks cần hiển thị trong phần chuẩn bị', related_name='used_in_preparations', through='content.PreparationBuildBlock', to='content.buildblock', verbose_name='Các khối xây dựng chuẩn bị'),
        ),
        migrations.AddField(
            model_name='preparation',
            name='lesson',
            field=models.OneToOneField(help_text='Mỗi bài học chỉ có một phần chuẩn bị', on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='content.lesson', verbose_name='Bài học'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type', 'order'], name='media_media_t_9796f0_idx'),
        ),
        migrations.AddField(
            model_name='lessonobjective',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='content.lesson', verbose_name='Bài học'),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='content.lesson', verbose_name='Bài học'),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='lesson_models', to='content.media', verbose_name='Media liên quan'),
        ),
        migrations.AddField(
            model_name='lessoncontentblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='content.lesson', verbose_name='Bài học'),
        ),
        migrations.AddField(
            model_name='lessoncontentblock',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='content_blocks', to='content.media', verbose_name='Media (Ảnh/Video)'),
        ),
        migrations.AddField(
            model_name='lessonattachment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.subcourse', verbose_name='Khóa học con'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='content.lesson', verbose_name='Bài học'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='content.media', verbose_name='Media (Ảnh/Video hướng dẫn)'),
        ),
        migrations.AddField(
            model_name='buildblock',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_blocks', to='content.program', verbose_name='Chương trình học'),
        ),
        migrations.AddField(
            model_name='assemblyguide',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_guides', to='content.lesson', verbose_name='Bài học'),
        ),
        migrations.AddField(
            model_name='assemblyguide',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='assembly_guides', to='content.media', verbose_name='Ảnh/Media hướng dẫn'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'is_completed'], name='user_progre_user_id_c01ae6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='subcourse',
            index=models.Index(fields=['program', 'status', 'sort_order'], name='subcourses_program_398b56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcourse',
            unique_together={('program', 'slug')},
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['quiz', 'user'], name='quiz_submis_quiz_id_e7374e_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['user', 'is_passed'], name='quiz_submis_user_id_9b748f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('quiz', 'user', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'question_type'], name='quiz_questi_quiz_id_5a0f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['quiz_submission', 'is_correct'], name='quiz_answer_quiz_su_0c0c03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('quiz_submission', 'question')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['lesson', 'status'], name='quizzes_lesson__3d1e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'is_correct'], name='question_op_questio_284133_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationbuildblock',
            index=models.Index(fields=['preparation'], name='preparation_prepara_fbdfe3_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationbuildblock',
            index=models.Index(fields=['build_block'], name='preparation_buildbl_074199_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preparationbuildblock',
            unique_together={('preparation', 'build_block')},
        ),
        migrations.AddIndex(
            model_name='lessonobjective',
            index=models.Index(fields=['lesson', 'objective_type'], name='lesson_obje_lesson__9326da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonobjective',
            unique_together={('lesson', 'objective_type', 'order')},
        ),
        migrations.AddIndex(
            model_name='lessonmodel',
            index=models.Index(fields=['lesson', 'order'], name='lesson_mode_lesson__6df8ce_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncontentblock',
            index=models.Index(fields=['lesson', 'order'], name='lesson_cont_lesson__e2066c_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['subcourse', 'status', 'sort_order'], name='lessons_subcour_bd1780_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subcourse', 'slug')},
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['lesson', 'difficulty', 'status'], name='challenges_lesson__241360_idx'),
        ),
        migrations.AddIndex(
            model_name='buildblock',
            index=models.Index(fields=['program', 'order'], name='build_block_program_7d56de_idx'),
        ),
        migrations.AddIndex(
            model_name='assemblyguide',
            index=models.Index(fields=['lesson'], name='assembly_gu_lesson__27ba4a_idx'),
        ),
    ]
