# Generated by Django 5.2.8 on 2025-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparation',
            name='build_blocks',
            field=models.ManyToManyField(blank=True, help_text='Chọn các build blocks cần hiển thị trong phần chuẩn bị', related_name='used_in_preparations', through='content.PreparationBuildBlock', through_fields=('preparation', 'build_block'), to='content.buildblock', verbose_name='Các khối xây dựng chuẩn bị'),
        ),
    ]
