# Generated by Django 5.2.8 on 2025-12-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_subcourse_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subtitle',
        ),
    ]
