# Generated by Django 5.2.8 on 2025-12-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_lesson_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='code_snippet',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='knowledge_skills',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='project_file_url',
        ),
    ]
