# Generated by Django 5.2.8 on 2025-12-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_lesson_code_snippet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
    ]
