# Generated by Django 5.2.8 on 2025-12-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_lesson_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='estimated_duration',
        ),
    ]
