# Generated by Django 5.2.8 on 2025-12-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_lesson_knowledge_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='knowledge_skills',
            field=models.TextField(blank=True, help_text='Các kiến thức và kỹ năng học được trong bài học', verbose_name='Kiến thức & Kỹ năng'),
        ),
    ]
